# Change these first
owner: mbove77 # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Fanalitica
    url: https://www.fanalitica.com
  - name: Atlas
    url: https://www.atlasfc.com.mx
  - name: Cruzados
    url: https://www.cruzados.cl
  - name: Puebla
    url: https://www.clubpuebla.com
  - name: Santos
    url: https://www.clubsantos.mx
  - name: Mazatlan
    url: https://www.mazatlanfc.com

status-website:
  theme: dark
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: https://mbove77.github.io/upptime
  baseUrl: /upptime
  logoUrl: https://ttpsrts.blob.core.windows.net/embed/assets/logofanalitica.png
  name: Fanalitica Web Status
  introTitle: "**Estado de las Webs de Fanalitica** "
  introMessage: En esta página se puede ver el estado de todas las webs que están bajo la supervisión de Fanalitica.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://mbove77.github.io/$REPO
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
